version: "3.2"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:${TAG:-latest}
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - STATS_USER=none
      - STATS_PASS=none
    secrets:
      - dfp_users_vfarcic
    deploy:
      labels:
        - com.df.notify=true
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 50M

  docs:
    image: vfarcic/docker-flow-proxy-docs:${TAG:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.reschedule=true
        - com.df.port=80
        - com.df.serviceDomain=proxy.dockerflow.com
        - com.df.servicePath=/
        - com.df.alertName.1=mem_limit
        - com.df.alertIf.1=@service_mem_limit:0.8
        - com.df.alertFor.1=30s
        - com.df.alertName.2=replicas_running
        - com.df.alertIf.2=@replicas_running
        - com.df.alertFor.2=1m
      replicas: 2
      resources:
        reservations:
          memory: 5M
        limits:
          memory: 10M

  letsencrypt:
    image: hamburml/docker-flow-letsencrypt:latest
    networks:
      - proxy
    environment:
      - DOMAIN_1=("dockerflow.com" "proxy.dockerflow.com" "swarmlistener.dockerflow.com" "monitor.dockerflow.com" "jenkins.dockerflow.com" "prometheus.dockerflow.com" "proxy-letsencrypt.dockerflow.com" "registry.dockerflow.com")
      - CERTBOT_EMAIL=viktor@farcic.com
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=("0 3 * * *" "0 15 * * *")
    volumes:
      - lets-encrypt:/etc/letsencrypt
    deploy:
      labels:
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.notify=true
        - com.df.port=80
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 30M

networks:
  proxy:
    external: true

secrets:
  dfp_users_vfarcic:
    external: true

volumes:
  lets-encrypt:
    driver: cloudstor:aws
    external: false